### ISSUE TITLE
Slowing down event loop

### ISSUE THREAD

**Issue by mogmog** [Melown/vts-browser-js#108]
I am trying to create a animated path, in a similar style to this http://zevross.com/blog/2014/09/30/use-the-amazing-d3-library-to-animate-a-path-on-a-leaflet-map/

I have got this far by hacking around on a jsfiddle : 

https://jsfiddle.net/hd6k7q0f/43/

But I have 2 issues that I do not know if the API supports. 

- Is it possible to slow down the event loop so that the line draws more slowly
- Is it possible to prevent the looping - ie the path is only drawn once.

**Comment by DavidLevinsky** [comment]
You can not control frequency of events. But you can control speed of changes. For example this way it draws line 10x slower:

https://jsfiddle.net/hd6k7q0f/48/

But more robust solution will be when you base change on elapsed time.

When you draw line dynamically then you have to use render event (loop in your terminology) every time for line rendering. Otherwise there will be no line when you change camera position and map is redrawn.
